site_name: SiteInterlock
site_url: http://rasbt.github.io/siteinterlock
site_author: Sebastian Raschka
site_description: A novel approach to pose selection in protein-ligand docking based on graph theory.

repo_url: https://github.com/rasbt/siteinterlock

docs_dir: sources
site_dir: html
theme: readthedocs

use_directory_urls: false
site_favicon: favicon.ico

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mathjax
extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - mathjaxhelper.js

copyright: Copyright &copy; 2016 Michigan State University

pages:
- Home: index.md
- Installation: installation.md
- User Guide: user_guide.md
- About:
  - Contact: contact.md
  - Release Notes: changelog.md
  - License: license.md
  - Citing SiteInterlock: cite.md
